title: "On-Call Weekly debrief - Week of <Month> <Day>, <Year>"
labels: ["assign:first-responder"]
body:
  - type: markdown
    attributes:
      value: |
        ## First Responder Debrief
  - type: textarea
    attributes:
      label: "🚦 Incidents"
      description: "Provide a brief summary of any internal or external Billing-related incidents that happened this week. Include links to the status.githubapp.com dashboard or the relevant github/availability issue."
  - type: textarea
    attributes:
      label: "🚨 Alerts"
      description: "Provide a brief summary of any alerts / monitors that have been firing more often than usual, and any known causes or mitigations applied."
  - type: textarea
    attributes:
      label: "🚧 Outstanding alerts"
      description: "Please list any alerts that are still critical and will need to be addressed by the incoming First Responder. See [Datadog](https://app.datadoghq.com/monitors/manage?q=status%3Aalert%20gitcoin&order=desc) for critical alerts."    
  - type: textarea
    attributes:
      label: "🎟️ Outstanding tickets"
      description: "Provide a brief summary and links to any outstanding customer support tickets that the incoming First Responder may have to pick up."
  - type: textarea
    attributes:
      label: "✏️ Other noteworthy things (e.g. pain points, wins, etc.)"
      description: "Anything else noteworthy that happened this week that doesn't fit into the other sections. Please also note any ad hoc tasks that came up (e.g. support plan uploads)."
